### ISSUE TITLE
Training my own model crashes my computer

### ISSUE THREAD

**Issue by LegitCamper** [rizki4106/netrade#6]
after preparing my own images in the file structure I ran this section of code. It crashes my computer every time. 

`from netrade.data import DataPreprocessing`

`# initialize class`
`chart = "neTrade/chart/"`
`candle = "neTrade/candle/"`

`prep = DataPreprocessing(chart_path=chart, candle_path=candle)`

`# create dataframe`
`frame = prep.create_frame()`

After running this about 30 seconds go by and then it soft-locks my computer. It could be that maybe I prepared too many images. I ran `tree | wc -l` to tell me how many total images I have. I have `30755` images split evenly between charts and candles. 

Any help diagnosing this issue would be very helpful.

**Comment by rizki4106** [comment]
I recommend you to use GPU

**Comment by rizki4106** [comment]
We will launch the REST API very soon, so we can use it easily. maybe next week

**Comment by LegitCamper** [comment]
Great! I look forward to that.

**Comment by rizki4106** [comment]
Hi now you can use netrade model through REST API call in just 3 easy steps, give it a try here [https://playground.heelmet.com/docs/netrade](https://playground.heelmet.com/docs/netrade)
